# Generated by Django 5.0.6 on 2024-05-27 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
